<?php http_response_code(404); ?>
<!doctype html>
<html>
<head>
    <title>Jerek's RPG Tools</title>
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/base.css">

    <style>
        div {font-size:24px; margin:100px 0 50px; text-align:center}
        h1 {font-size:150px; font-weight:900; margin:0 0 20px; opacity:.25}

        @media (max-width:1400px) {
            h1 {font-size:100px}
        }

        @media (max-width:950px) {
            h1 {font-size:75px}
        }

        @media (max-width:675px) {
            h1 {font-size:50px}
        }

        @media (max-width:475px) {
            div {font-size:18px}
            h1 {font-size:40px}
        }

        @media (max-width:375px) {
            h1 {font-size:30px}
        }
    </style>
</head>
<body>

<div>
    <h1>404 Not Found</h1>
    <a href="/">&laquo; Home Page</a>
</div>

</body>
</html>
